
export const CREATE_USERS_TABLE = 'CREATE TABLE IF NOT EXISTS users (id  INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT NOT NULL UNIQUE, password TEXT NOT NULL, created_at TEXT DEFAULT CURRENT-TIMESTAMP);';

export const CREATE_INVENTORY_TABLE = 'CREATE TABLE IF NOT EXISTS inventory (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, name TEXT NOT NULL, description TEXT, category TEXT NOT NULL, url_image TEXT NOT NULL, amount REAL NOT NULL, updated_at TEXT DEFAULT CURRENT-TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE);';
    
export const ENABLE_FOREIGN_KEYS = 'PRAGMA foreign_keys = ON;';

export const ALL_TABLES = [ENABLE_FOREIGN_KEYS, CREATE_USERS_TABLE, CREATE_INVENTORY_TABLE];